# Generated by Django 4.0.3 on 2022-03-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(blank=True, default='null', upload_to='')),
                ('location', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=255)),
            ],
        ),
    ]
