# Generated by Django 4.0.2 on 2022-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Please select a drink type'), ('A', 'Americano'), ('C', 'Cappuccino'), ('CB', 'Cold Brew Coffee')], max_length=10)),
                ('size', models.CharField(choices=[(None, 'Please select a size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Please select a drink type'), ('A', 'Americano'), ('C', 'Cappuccino'), ('CB', 'Cold Brew Coffee')], max_length=10)),
                ('size', models.CharField(choices=[(None, 'Please select a size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
    ]
